R3Sm1th/-rails-renteaze

.gitignore
Gemfile
Gemfile.lock
app/models/property.rb
app/views/pages/home.html.erb
config/environments/development.rb
config/storage.yml
db/migrate/20230613100708_create_active_storage_tables.active_storage.rb
db/schema.rb

Cloudinary has been implement up to the SEED part !

Cloudinary

---

Gemfile.lock
app/controllers/properties_applications_controller.rb
app/views/property_applications/index.html.erb
config/routes.rb

added features to properties_applications : CRUD and INDEX : controller / views

properties applications set up

---

app/controllers/property_applications_controller.rb
app/models/property_application.rb
app/views/property_applications/_form.html.erb
app/views/property_applications/_property_applications.html.erb
app/views/property_applications/edit.html.erb
app/views/property_applications/index.html.erb
app/views/property_applications/new.html.erb
app/views/property_applications/show.html.erb
config/routes.rb
db/migrate/20230613141358_edit_associations_for_property_applications.rb
db/schema.rb

Property Applications paths updated

property applications updated

---

app/views/property_applications/index.html.erb

CRUD for property_application

---

app/controllers/property_applications_controller.rb
app/views/pages/home.html.erb
app/views/properties/_property.html.erb
app/views/properties/index.html.erb
app/views/property_applications/_property_application.html.erb
app/views/property_applications/_property_applications.html.erb
app/views/property_applications/index.html.erb
app/views/property_applications/show.html.erb

Added bootstrap to applications page and getting my head around CASE statemte

Sussingout

---

app/controllers/bank_references_controller.rb
app/controllers/property_applications_controller.rb
app/views/bank_references/edit.html.erb
app/views/bank_references/new.html.erb
app/views/property_applications/_property_application.html.erb
app/views/property_applications/show.html.erb
config/routes.rb

ROutes Updated
Application Showpage fixed
New Bank References pages + button

Applications Show Page and Route update

---

app/assets/stylesheets/components/_background-white.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_btn-banner.scss
app/assets/stylesheets/components/_btn-navbar.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_homeh1.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/pages/_banner.html.erb
app/views/pages/_card.html.erb
app/views/pages/_firstcard.html.erb
app/views/pages/_footer.html.erb
app/views/pages/_secondcard.html.erb
app/views/pages/_thirdcard.html.erb
app/views/pages/home.html.erb
app/views/pages/uitest.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

Homepage has been implemented but using a different html which is uitest.

Homepage implemented

---

app/controllers/employment_documents_controller.rb
app/models/employment_document.rb
app/views/employment_documents/new.html.erb
app/views/property_applications/show.html.erb
config/routes.rb
db/migrate/20230614135138_add_property_application_id_to_employment_documents.rb
db/schema.rb

show and edit action is still needed, sorry for the delay

employment document push process - new and create action finished, tbf

---

app/assets/stylesheets/components/_background-white.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_btn-banner.scss
app/assets/stylesheets/components/_btn-navbar.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_homeh1.scss
app/assets/stylesheets/components/_homep.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_fonts.scss

CSS rule has been added to change all the fonts.

Fonts have been changed

---

app/controllers/employment_documents_controller.rb
app/models/employment_document.rb
app/views/employment_documents/edit.html.erb
app/views/employment_documents/index.html.erb
app/views/employment_documents/new.html.erb
app/views/employment_documents/show.html.erb
app/views/property_applications/show.html.erb
config/routes.rb

employment list link is provided in the main application show page, where you can delete as well. 
once you create your document, it takes you to show page, where you can either  1. edit 2. delete or 3. return to application page

completed employment actions

---

app/controllers/property_applications_controller.rb
app/views/identifications/_id.html.erb
app/views/property_applications/confirm.html.erb
config/routes.rb

this feature is completed, its a button_to instead of link_to, for some obscure reason. You can find it at the bottom of the application show page, they need to be styled :)

completed the accept and decline button on the application show page

---

app/controllers/bank_references_controller.rb
app/views/bank_references/_form.html.erb
app/views/bank_references/create.turbo_stream.erb
app/views/bank_references/edit.html.erb
app/views/bank_references/new.html.erb
app/views/bank_references/show.html.erb
app/views/pages/_firstcard.html.erb
app/views/pages/_secondcard.html.erb
app/views/pages/_thirdcard.html.erb
app/views/shared/_navbar.html.erb

Bank Ref Turbo Frame updated, Updated Buttons and some homepage text

Bank Ref updated and Home Page Buttons

---

app/assets/stylesheets/components/_card.scss
app/views/employment_documents/new.html.erb
app/views/identifications/new.html.erb
app/views/pages/_firstcard.html.erb
app/views/pages/_secondcard.html.erb
app/views/pages/_thirdcard.html.erb
app/views/properties/edit.html.erb
app/views/properties/index.html.erb
app/views/property_applications/_property_application.html.erb
app/views/property_applications/index.html.erb

- property index layout fixed;
- other layouts have been also fixed;
- few buttons changed;

Style some pages and fix property index layout

---

app/controllers/property_applications_controller.rb

button finished

---

Gemfile.lock
app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/map_controller.js

commented out setup part for flatpicker, Clement will raise ticket with TA.

map not showing due to flatpicker setup conflict

---

app/views/property_applications/_tenant_property_application.html.erb

If else statement set to finalize tenant application

My applications updated

---

app/assets/stylesheets/application.scss
app/javascript/controllers/flatpickr_controller.js
app/views/property_applications/finalize.html.erb

flatpickr added to finalize page

flatpickr added to finalize page

---

app/views/property_applications/_property_application.html.erb
app/views/property_applications/_tenant_property_application.html.erb

Links fixed : link to finalize application from landlord side

Links fixed

---

app/controllers/bank_references_controller.rb
app/views/bank_references/index.html.erb
app/views/property_applications/_landlord_application_show.html.erb

Might need to building in defences in, via validations tomorrow

banking references

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_message.scss
app/models/chatroom.rb
app/models/user.rb
app/views/property_application_finalize/_chatbox.html.erb
app/views/property_applications/finalize.html.erb

Agent has the power to select move in date for user, tenant will see "tbd" if no move in date is confirmed. otherwise, tenant will see the updated move in date once agent has submit move in date

completed the design, confirm button applied to agent only

---

app/controllers/property_applications_controller.rb
app/views/property_applications/finalize.html.erb
db/seeds.rb

- added information on the seeds
- centered the features on finalize page so its half and half
- edited the confirm your move in date with your landlord/tenant, with a logic in the html
- bolded the move in date so it is more obvious

completed tweaking seeds and finalize page

---

app/views/properties/_property.html.erb
app/views/properties/index.html.erb
app/views/property_applications/_landlord_application_show.html.erb
app/views/property_applications/_tenant_application_show.html.erb
app/views/property_applications/_tenant_property_application.html.erb
app/views/property_applications/my_applications.html.erb

my applications file edited
links added to card-hovers
styling

my applications and landlors links done

---

app/assets/stylesheets/components/_approvedbtn.scss
app/assets/stylesheets/components/_buttontrial.scss
app/assets/stylesheets/components/_buttontrialtwo.scss
app/assets/stylesheets/components/_declinedbtn.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_pendingbtn.scss
app/views/pages/_approvedbtn.html.erb
app/views/pages/_buttontrial.html.erb
app/views/pages/_declinedbtn.html.erb
app/views/pages/_pendingbtn.html.erb
app/views/pages/uitest.html.erb
app/views/property_applications/_tenant_property_application.html.erb

- new buttons implemented;
- layout improved;

2 beautiful buttons implemented and other tweaks made
